# 工作流的名称
name: Build and Deploy Frontend Project

# 触发条件：当有代码 push 到 master 分支时触发
on:
  push:
    branches:
      - master

# 任务列表
jobs:
  build-and-deploy:
    # 这里的标签必须和您注册 Runner 时设置的标签完全一致
    runs-on: windows-iis

    # 任务包含的步骤
    steps:
      # 第1步：检出代码
      - name: Checkout Repository
        uses: C:/Program Files/gitea-runner/actions-local/actions/checkout

      # 第2步：设置 Node.js 环境
      - name: Setup Node.js
        uses: C:/Program Files/gitea-runner/actions-local/actions/setup-node
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'opsboard-frontend/package-lock.json'

      # 第3步：安装依赖并执行构建
      - name: Install Dependencies and Build
        working-directory: ./opsboard-frontend
        run: |
          echo "==> Installing dependencies in $(pwd)..."
          npm install
          echo "==> Building project in $(pwd)..."
          npm run build

      # 第4步：部署到 IIS 网站目录
      - name: Deploy to IIS Directory
        shell: powershell
        run: |
          $sourceBuildPath = ".\opsboard-frontend\dist"
          $sourceConfigPath = ".\web.config"
          $destinationPath = "C:\inetpub\wwwroot\opsboard-web"
          
          Write-Host "Source path: $sourceBuildPath"
          Write-Host "Destination path: $destinationPath"
          
          if (-not (Test-Path $destinationPath)) {
            Write-Host "Destination directory does not exist. Creating it..."
            New-Item -ItemType Directory -Force -Path $destinationPath
          }
          
          Write-Host "Clearing destination directory..."
          Remove-Item -Recurse -Force -Path "$destinationPath\*"
          
          Write-Host "Copying build artifacts..."
          Copy-Item -Path "$sourceBuildPath\*" -Destination $destinationPath -Recurse -Force
          
          Write-Host "Copying web.config..."
          Copy-Item -Path $sourceConfigPath -Destination $destinationPath -Force
          
          Write-Host "Deployment successful!"