# 工作流的名称
name: Build and Deploy Frontend Project

# 触发条件：当有代码 push 到 master 分支时触发
on:
  push:
    branches:
      - master

# 任务列表
jobs:
  build-and-deploy:
    # 这里的标签必须和您注册 Runner 时设置的标签完全一致
    runs-on: windows-iis

    # 任务包含的步骤
    steps:
      # 第1步：检出代码
      # 恢复为标准格式。这将依赖于您 Runner 服务器上的本地缓存或回退机制。
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 第2步：设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'opsboard-frontend/package-lock.json'

      # 第3步：安装依赖并执行构建
      - name: Install Dependencies and Build
        working-directory: ./opsboard-frontend
        run: |
          npm install
          npm run build

      # 第4步：部署到 IIS 网站目录
      - name: Deploy to IIS Directory
        shell: powershell
        run: |
          $sourceBuildPath = ".\opsboard-frontend\dist"
          $destinationPath = "C:\inetpub\wwwroot\opsboard-web"
          
          Write-Host "Preparing deployment to $destinationPath..."
          if (-not (Test-Path $destinationPath)) {
            New-Item -ItemType Directory -Force -Path $destinationPath
          }
          Remove-Item -Recurse -Force -Path "$destinationPath\*"
          
          Write-Host "Copying build artifacts..."
          Copy-Item -Path "$sourceBuildPath\*" -Destination $destinationPath -Recurse -Force
          
          # [核心修复] 直接在 Runner 中创建 web.config 文件
          Write-Host "Creating web.config for SPA routing..."
          $webConfigContent = @"
          <?xml version="1.0" encoding="UTF-8"?>
          <configuration>
            <system.webServer>
              <rewrite>
                <rules>
                  <rule name="React-Router Rule" stopProcessing="true">
                    <match url=".*" />
                    <conditions logicalGrouping="MatchAll">
                      <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                      <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
                    </conditions>
                    <action type="Rewrite" url="/" />
                  </rule>
                </rules>
              </rewrite>
            </system.webServer>
          </configuration>
          "@
          
          # 使用 Set-Content 将内容写入文件，并指定 UTF8 编码
          Set-Content -Path "$destinationPath\web.config" -Value $webConfigContent -Encoding UTF8
          
          Write-Host "Deployment successful!"