# 工作流的名称
name: Build and Deploy Frontend Project

# 触发条件：当有代码 push 到 master 分支时触发
on:
  push:
    branches:
      - master

# 任务列表
jobs:
  build-and-deploy:
    # 关键！这里的标签必须和您注册 Runner 时设置的标签完全一致
    runs-on: windows-iis

    # 任务包含的步骤
    steps:
      # 第1步：检出代码
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 第2步：设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # 请根据您的项目要求，指定正确的 Node.js 版本

      # 第3步：安装依赖并执行构建
      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build

      # 第4步：部署到 IIS 网站目录
      - name: Deploy to IIS Directory
        run: |
          Copy-Item -Path ./dist/* -Destination C:\inetpub\wwwroot\opsboard-web -Recurse -Force