# 工作流的名称
name: Build and Deploy Full Stack Project

# 触发条件：当有代码 push 到 master 分支时触发
on:
  push:
    branches:
      - master

# 任务列表
jobs:
  build-and-deploy:
    # 运行环境：在自托管的 Windows IIS 服务器上运行
    runs-on: windows-iis

    # 环境变量：定义整个任务中使用的路径变量，方便管理
    env:
      FRONTEND_DIR: ./opsboard-frontend
      BACKEND_DIR: ./opsboard-backend
      DEPLOY_DIR: C:\inetpub\wwwroot\opsboard-web

    # 任务包含的步骤
    steps:
      # 第1步：检出代码
      # 从代码仓库拉取最新代码到 Runner 的工作区
      - name: Checkout Repository
        uses: actions/checkout@v4

      # ------------------- 后端构建部分 -------------------
      # 第2步：设置 Go 环境
      # 安装并配置指定版本的 Go 语言环境
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25' # 您可以指定一个更具体的版本，如 '1.22.2'，以确保环境一致性
          cache: true # 启用 Go 模块缓存，加快后续构建速度

      # 第3步：设置 Go 模块代理
      # 将 Go 模块代理设置为 goproxy.cn，解决国内访问 proxy.golang.org 的网络问题
      - name: Set Go Proxy
        run: go env -w GOPROXY=https://goproxy.cn,direct
        shell: cmd # 使用 cmd 或 powershell 均可

      # 第4步：下载 Go 依赖项
      # 使用 `go mod tidy` 整理和下载后端项目所需的所有依赖包
      - name: Install Go Dependencies
        working-directory: ${{ env.BACKEND_DIR }}
        run: go mod tidy

      # 第5步：构建 Go 后端应用
      # 将 Go 源代码编译成一个 Windows 可执行文件 (opsboard-backend.exe)
      - name: Build Go Backend
        working-directory: ${{ env.BACKEND_DIR }}
        run: go build -o opsboard-backend.exe .

      # ------------------- 前端构建部分 -------------------
      # 第6步：设置 Node.js 环境
      # 安装并配置指定版本的 Node.js 环境，用于构建前端项目
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm' # 启用 npm 缓存
          # 指定缓存依赖路径，确保缓存的准确性
          cache-dependency-path: '${{ env.FRONTEND_DIR }}/package-lock.json'

      # 第7步：安装前端依赖并执行构建
      # 首先安装 package.json 中定义的所有依赖，然后执行构建脚本（如 Vue/React 的 build）
      - name: Install Dependencies and Build Frontend
        working-directory: ${{ env.FRONTEND_DIR }}
        run: |
          npm install
          npm run build

      # ------------------- 部署部分 -------------------
      # 第8步：部署所有构建产物到 IIS 目录
      # 使用 PowerShell 脚本执行部署操作
      - name: Deploy to IIS Directory
        shell: powershell
        run: |
          Write-Host "Preparing deployment to ${{ env.DEPLOY_DIR }}..."
          # 检查目标目录是否存在，如果不存在则创建
          if (-not (Test-Path "${{ env.DEPLOY_DIR }}")) {
            New-Item -ItemType Directory -Force -Path "${{ env.DEPLOY_DIR }}"
          }
          
          # 定义服务名称，方便后续引用
          $serviceName = "opsboard-backend-service"
          # 检查服务是否存在，如果存在则先停止它，以便安全地更新文件
          if (Get-Service $serviceName -ErrorAction SilentlyContinue) {
            Write-Host "Stopping service '$serviceName'..."
            Stop-Service -Name $serviceName -Force
          }

          # 清空部署目录，但保留日志文件，以便排查问题
          Write-Host "Clearing destination directory (excluding logs)..."
          Get-ChildItem -Path "${{ env.DEPLOY_DIR }}" -Exclude "stdout.log", "stderr.log" | Remove-Item -Recurse -Force
          
          # 复制前端构建产物（通常在 dist 目录下）到部署目录
          Write-Host "Copying frontend build artifacts..."
          Copy-Item -Path "${{ env.FRONTEND_DIR }}\dist\*" -Destination "${{ env.DEPLOY_DIR }}" -Recurse -Force
          
          # 复制后端可执行文件
          Write-Host "Copying backend executable..."
          Copy-Item -Path "${{ env.BACKEND_DIR }}\opsboard-backend.exe" -Destination "${{ env.DEPLOY_DIR }}" -Force
          
          # 复制后端环境变量配置文件
          Write-Host "Copying backend configuration (.env)..."
          Copy-Item -Path "${{ env.BACKEND_DIR }}\.env" -Destination "${{ env.DEPLOY_DIR }}" -Force
          
          # 复制 IIS 配置文件
          Write-Host "Copying web.config..."
          Copy-Item -Path ".\web.config" -Destination "${{ env.DEPLOY_DIR }}" -Force
          
          Write-Host "Deployment successful!"

      # 第9步：使用 NSSM 创建或启动 Go 后端服务
      # 无论前面步骤是否成功都执行此步骤，确保服务在部署后处于正确的状态
      - name: Create or Start Go Backend Service with NSSM
        if: always() # `always()` 确保即使构建失败，此步骤也会运行，尝试重启服务
        shell: powershell
        run: |
          $serviceName = "opsboard-backend-service"
          # 检查 NSSM 是否安装并存在于系统 PATH 中
          if (-not (Get-Command nssm -ErrorAction SilentlyContinue)) {
            Write-Error "NSSM is not found in PATH. Please install it on the runner server."
            exit 1
          }

          # 检查服务是否已创建，如果未创建，则使用 NSSM 安装并配置它
          if (-not (Get-Service $serviceName -ErrorAction SilentlyContinue)) {
            Write-Host "Service '$serviceName' not found. Creating it..."
            nssm install $serviceName "${{ env.DEPLOY_DIR }}\opsboard-backend.exe"
            nssm set $serviceName AppDirectory "${{ env.DEPLOY_DIR }}"
            nssm set $serviceName AppStdout "${{ env.DEPLOY_DIR }}\stdout.log"
            nssm set $serviceName AppStderr "${{ env.DEPLOY_DIR }}\stderr.log"
            nssm set $serviceName Start SERVICE_AUTO_START
          }
          
          # [关键优化] 在启动服务前，检查可执行文件是否存在
          $executablePath = "${{ env.DEPLOY_DIR }}\opsboard-backend.exe"
          if (-not (Test-Path $executablePath)) {
            Write-Error "Backend executable not found at '$executablePath'. Build or Deploy step may have failed. Skipping service start."
            exit 1 # 文件不存在，说明构建或部署失败，此步骤也标记为失败
          }
          
          # 如果文件存在，则启动服务
          Write-Host "Starting service '$serviceName'..."
          Start-Service -Name $serviceName
          
          Write-Host "Service '$serviceName' is running."