name: Deploy to Windows Server IIS

# 触发条件：当代码被推送到 master 分支时
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    # 关键！这里的名称必须和你注册 Runner 时设置的标签(label)完全一致
    runs-on: windows-iis

    steps:
      # 第1步：从Gitea仓库拉取最新代码
      # 这一步在根目录执行，无需修改
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      # 第2步：安装和设置你项目所需的 Node.js 版本
      # 这一步是全局设置，无需修改
      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: '18' # 你可以根据需要更改此版本

      # 第3步：安装项目依赖 (npm install)
      # !!! 修改点: 指定工作目录为前端项目文件夹
      - name: Install dependencies
        working-directory: ./opsboard-frontend
        run: npm install

      # 第4步：构建项目 (npm run build)，生成静态文件
      # !!! 修改点: 指定工作目录为前端项目文件夹
      - name: Build project
        working-directory: ./opsboard-frontend
        run: npm run build

      # 第5步：部署到 IIS 网站目录
      # !!! 修改点: 指定工作目录为前端项目文件夹，这样才能找到构建产物 dist 目录
      - name: Deploy to IIS
        working-directory: ./opsboard-frontend
        shell: powershell
        run: |
          # --- 请确认下面的配置 ---
          # 1. 你的 IIS 网站在服务器上的物理路径
          $targetPath = "C:\inetpub\wwwroot\opsboard-web" 
          
          # 2. 你的网站在 IIS 中对应的“应用程序池”的名称
          $appPoolName = "opsboard-web" 
          # --- 配置结束 ---

          Write-Host "Stopping Application Pool: $appPoolName"
          Stop-WebAppPool -Name $appPoolName
          
          Write-Host "Clearing old files from destination: $targetPath"
          # 清空目标文件夹里的旧文件
          Remove-Item -Path (Join-Path $targetPath "*") -Recurse -Force
          
          Write-Host "Copying new build files to $targetPath"
          # 因为当前工作目录已经是 opsboard-frontend，所以可以直接从 .\dist\ 复制
          Copy-Item -Path ".\dist\*" -Destination $targetPath -Recurse -Force
          
          Write-Host "Starting Application Pool: $appPoolName"
          Start-WebAppPool -Name $appPoolName
          
          Write-Host "Deployment to IIS completed successfully!"