# 工作流的名称
name: Build and Deploy Frontend Project

# 触发条件：当有代码 push 到 master 分支时触发
on:
  push:
    branches:
      - master

# 任务列表
jobs:
  build-and-deploy:
    # 这里的标签必须和您注册 Runner 时设置的标签完全一致
    runs-on: windows-iis

    # 任务包含的步骤
    steps:
      # 第1步：检出代码
      # 使用标准语法，这将利用您 Runner 的本地缓存/回退机制
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 第2步：设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'opsboard-frontend/package-lock.json'

      # 第3步：安装依赖并执行构建
      - name: Install Dependencies and Build
        working-directory: ./opsboard-frontend
        run: |
          npm install
          npm run build

      # 第4步：部署到 IIS 网站目录
      - name: Deploy to IIS Directory
        shell: powershell
        run: |
          $sourceBuildPath = ".\opsboard-frontend\dist"
          # [核心修复] 将源路径指向仓库根目录下的 web.config
          $sourceConfigPath = ".\web.config"
          $destinationPath = "C:\inetpub\wwwroot\opsboard-web"
          
          Write-Host "Preparing deployment to $destinationPath..."
          if (-not (Test-Path $destinationPath)) {
            New-Item -ItemType Directory -Force -Path $destinationPath
          }
          Remove-Item -Recurse -Force -Path "$destinationPath\*"
          
          Write-Host "Copying build artifacts from $sourceBuildPath..."
          Copy-Item -Path "$sourceBuildPath\*" -Destination $destinationPath -Recurse -Force
          
          # [核心修复] 明确地将根目录的 web.config 复制到部署目录
          Write-Host "Copying web.config from $sourceConfigPath..."
          Copy-Item -Path $sourceConfigPath -Destination $destinationPath -Force
          
          Write-Host "Deployment successful!"