name: Deploy to Windows Server IIS

# 触发条件：当代码被推送到 main 分支时
on:
  push:
    branches:
      - master # 如果你的主分支是 master，请修改为 master

jobs:
  build-and-deploy:
    # 关键！这里的名称必须和你注册 Runner 时设置的标签(label)完全一致
    runs-on: windows-iis

    steps:
      # 第1步：从Gitea仓库拉取最新代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 第2步：安装和设置你项目所需的 Node.js 版本
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # <-- 修改为你项目需要的 Node.js 版本

      # 第3步：安装项目依赖 (npm install)
      - name: Install dependencies
        run: npm install

      # 第4步：构建项目 (npm run build)，生成静态文件
      - name: Build project
        run: npm run build

      # 第5步：部署到 IIS 网站目录
      - name: Deploy to IIS
        # 使用 PowerShell 执行部署脚本
        shell: powershell
        run: |
          # --- 请修改下面的配置 ---
          # 1. 你的 IIS 网站在服务器上的物理路径
          $targetPath = "C:\inetpub\wwwroot\opsboard-web" 
          
          # 2. 你的网站在 IIS 中对应的“应用程序池”的名称
          $appPoolName = "opsboard-web" 
          # --- 配置结束 ---

          Write-Host "Stopping Application Pool: $appPoolName"
          Stop-WebAppPool -Name $appPoolName
          
          Write-Host "Clearing old files from destination: $targetPath"
          # 清空目标文件夹里的旧文件
          Remove-Item -Path (Join-Path $targetPath "*") -Recurse -Force
          
          Write-Host "Copying new build files to $targetPath"
          # 将构建好的 dist 文件夹里的所有内容复制到目标路径
          Copy-Item -Path ".\dist\*" -Destination $targetPath -Recurse -Force
          
          Write-Host "Starting Application Pool: $appPoolName"
          Start-WebAppPool -Name $appPoolName
          
          Write-Host "Deployment to IIS completed successfully!"